# Generated by Django 5.0.1 on 2024-02-20 14:54

import DoughliciousApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoughliciousApp', '0003_deliverydetails_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydetails',
            name='expDate',
            field=models.DateField(default='', validators=[DoughliciousApp.validators.validate_date_format]),
        ),
    ]
